"""Add bets and participants

Revision ID: 2d4653ea2ef5
Revises: de34ec1d495d
Create Date: 2025-10-18 14:51:05.931437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d4653ea2ef5'
down_revision = 'de34ec1d495d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bets',
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bet_type', sa.Enum('TEAM', 'PLAYER', 'CUSTOM', name='bettype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SETTLED', 'CANCELLED', name='betstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('bet_id')
    )
    op.create_table('bet_participants',
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.bet_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('participant_id'),
    sa.UniqueConstraint('bet_id', 'user_id', name='uq_bet_user')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    op.drop_table('bet_participants')
    op.drop_table('bets')
    # ### end Alembic commands ###
