"""Add position_a and position_b to bets, remove position from participants

Revision ID: 4e1de6587e8e
Revises: 2d4653ea2ef5
Create Date: 2025-10-18 15:45:18.718976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1de6587e8e'
down_revision = '2d4653ea2ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_participants', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
