"""Add position_a and position_b to bets

Revision ID: 7f62f10f5368
Revises: 4e1de6587e8e
Create Date: 2025-10-18 16:01:00.051323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f62f10f5368'
down_revision = '4e1de6587e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_a', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('position_b', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.drop_column('position_b')
        batch_op.drop_column('position_a')

    # ### end Alembic commands ###
